@startjson
{
    "registration_info":
    {
        "name": "",
        "organization": "",
        "address": ""
    },
    "type": "",
    "registration_credentials": {
        "username": "",
        "token": ""
    }
}
@endjson